<html>
<?php include('head.html'); ?>
<body class="min-vh-100 d-flex flex-column">
<?php include('header.html'); ?>

<?php if (isset($flash['warning'])) : ?>
    <div class="alert alert-warning" role="alert">
        <?php print_r($flash['warning'][0]); ?>
    </div>
<?php endif; ?>
  
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
                      <h1>Упс что-то пошло не так</h1>
                    <div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
  <div class="col">
    <h2 class="h2 mb-4">
      Ошибка 500
    </h2>
  </div>
</div>
        </div>
    </main>
    <?php include('footer.html'); ?>
</body>
</html>