<html>
<?php include('head.html'); ?>
<body class="min-vh-100 d-flex flex-column">
<?php include('header.html'); ?>

    <?php if (isset($flash['success'])) : ?>
    <div class="alert alert-success" role="alert">
        <?php print_r($flash['success'][0]); ?>
    </div>
    <?php endif; ?>
    <?php if (isset($flash['error'])) : ?>
    <div class="alert alert-danger" role="alert">
        <?php print_r($flash['error'][0]); ?>
  </div>
    <?php endif; ?>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
                      <h1>Сайт: <?= $url['name'] ?></h1>
                      <div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="url">
      <tbody>
        <tr>
          <td>ID</td>
          <td><?= $url['id'] ?></td>
        </tr>
        <tr>
          <td>Имя</td>
          <td><?= $url['name'] ?></td>
        </tr>
        <tr>
          <td>Дата создания</td>
          <td><?= $url['created_at'] ?></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h2 class="mt-5 mb-3">Проверки</h2>
  <form method="post" action="/urls/<?= $url['id'] ?>/checks">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
  </form>
  <table class="table table-bordered table-hover" data-test="checks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($check as $values) : ?>
      <tr>
        <td><?= $values['id'] ?></td>
        <td><?= $values['status_code'] ?></td>
        <td><?= $values['h1'] ?></td>
        <td><?= $values['title'] ?></td>
        <td><?= $values['description'] ?></td>
        <td><?= $values['created_at'] ?></td>
      </tr>
      <?php endforeach; ?>
          </tbody>
  </table>
        </div>
    </main>
    <?php include('footer.html'); ?>
</body>
</html>
